language: node_js
env:
  global:
    - NODE_ENV=travisci
node_js:
  - "0.10.40"
before_install:
  - mv lib/config/template/development.json config/travisci.json
  - cp config/travisci.json config/common.json
  - cp config/travisci.json config/test.json
  - npm install -g nodemon
  - npm install
  - npm install -g grunt-cli
  - npm cache clean
before_script:
  - psql -c 'create database copcastdb_test;' -U postgres
script:
  - "grunt test"
